version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .:/app/node_modules
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
